### ISSUE TITLE
Make public record URLs redirect both ways

### ISSUE THREAD

**Issue by hurtstotouchfire** [openedx/frontend-app-learner-record#108]
With the Learner Record MFE on track to become a mandatory part of Credentials, replacing the legacy frontend of the records app in the IDA, we must ensure that we continue supporting public program record links that learners have already created and shared.

Anyone who is trying to access a public program record in the old experience must be redirected to the Learner Record MFE.

We are planning on using an application level redirect, taking advantage of Django’s built-in functionality to redirect learners to the MFE. For more information on what influenced this decision, see this Spike [doc](https://docs.google.com/document/d/1cydoTTkbENWBD6Edw_-aahQ25SVYX1926lf3i4kkgPM/edit?usp=sharing) and read the Link Redirection section.

We are looking to redirect users who hit a public program record at [https://credentials.edx.org/records/programs/shared/{shared_program_record_uuid}/](https://credentials.edx.org/records/programs/shared/%7Bshared_program_record_uuid%7D/) to [https://records.edx.org/shared/{shared_program_record_uuid}/](https://records.edx.org/shared/%7Bshared_program_record_uuid%7D/).

We may want to re-use the [existing view](https://github.com/openedx/credentials/blob/8db780046eab244fea4c2de5d9facbd08239baf2/credentials/apps/records/views.py#L149-L197) in Credentials to perform the redirect. Currently, both the public and private program records use the same view. We may want to change this going forward to better support deprecation of the old views.

We can toggle this functionality using the USE_LEARNER_RECORD_MFE setting. If enabled, we will redirect/rewrite the link to the Learner Record MFE. If disabled, we will continue to render the program record in Credentials using the legacy FE. 

### Acceptance Criteria

The Credentials IDA supports redirection of public program record links to the Learner Record MFE.

The redirection functionality can be toggled using an existing setting (USE_LEARNER_RECORD_MFE).

Make any required updates in the Learner Record and Support Tools MFEs.

**Comment by hurtstotouchfire** [comment]
PRs for this work: 
Credentials PR: https://github.com/openedx/credentials/pull/1793
LR MFE PR: https://github.com/openedx/frontend-app-learner-record/pull/105
Support Tools MFE PR: https://github.com/openedx/frontend-app-support-tools/pull/276

**Comment by arbrandes** [comment]
Looks like this is done.
