### ISSUE TITLE
frontend-app-learner-record Initial Maintenance

### ISSUE THREAD

**Issue by feanil** [openedx/frontend-app-learner-record#133]
- [x] Github Issues is Enabled
- [x] A `catalog-info.yaml` file exists
- [x] Dependency Update Automation is Enabled
- [x] A well-formed README exists.

[Details and links to how-tos.](https://docs.openedx.org/en/latest/developers/how-tos/maintain-a-repo.html)

**Comment by jsnwesson** [comment]
A Jira ticket was created in Aperture's internal board, and this will be addressed in an upcoming grooming session. 
Note: I'm certain that most of these have already been done, except for the Dependency Update automation

**Comment by deborahgu** [comment]
the only step pending on this is Dependency Update Automation, and Aperture needs axim to do this because we don't have admin privileges for the repo. Can you assist, @feanil?

**Comment by feanil** [comment]
@deborahgu I've added the relevant bot team to the repo, you should be all set to add the workflow per https://docs.openedx.org/en/latest/developers/how-tos/enable-python-upgrade-automation.html 

Let me know if you run into issues or feel free to make a PR to update the doc and tag me for review.

**Comment by deborahgu** [comment]
all done, we should keep an eye to make sure it does the thing.
