### ISSUE TITLE
UX Review for creating verifiable credentials

### ISSUE THREAD

**Issue by e0d** [openedx/frontend-app-learner-record#136]
As part of FC-0006, new screens are required to allow users to share their credentials with external networks.  In the initial case, functionality will be focused on sharing credential to the Digital Credential Consortium wallet application.

Folks at RaccoonGang have created [Figma mock-ups](https://www.figma.com/file/DuUoJaq0nG2TU3WCPPLUBG/Verifiable-Credentials?node-id=0%3A1&t=ZM6d00gQAOypb7bF-0) for review and comment. 

We currently believe that all required UI elements are provided by Paragon components.

FYI @hurtstotouchfire

**Comment by e0d** [comment]
@gabew1984 There was a small change made to accommodate the case where a single instance of the platform might support multiple credentials backends, https://www.figma.com/proto/DuUoJaq0nG2TU3WCPPLUBG?node-id=183:777#379559554

**Comment by GlugovGrGlib** [comment]
Implemented in the https://github.com/openedx/frontend-app-learner-record/pull/151

**Comment by deborahgu** [comment]
marking this as done because the functionality was implemented, so I'm assuming the UX review happened.

**Comment by justinhynes** [comment]
Based on the previous few comments, it sounded like this was complete. Please let me know if this is an error on my part and we can reopen.

**Comment by GlugovGrGlib** [comment]
That's correct, this was completed. Thanks!
