### ISSUE TITLE
Enable Renovate via GitHub Action

### ISSUE THREAD

**Issue by jsnwesson** [openedx/frontend-app-learner-record#157]
The Renovate bot was at one point updating the frontend dependencies for Learner Record until Fall 2022. Since then, it still has a `renovate.json` file that was updated four months ago, but Renovate is not currently active.

**Comment by hurtstotouchfire** [comment]
Did we determine that we need to put in a ticket with Axim for this?

**Comment by jsnwesson** [comment]
The ticket for this exists in the team's backlog!
https://2u-internal.atlassian.net/browse/APER-2864

**Comment by deborahgu** [comment]
this is done, though I'm keeping an eye on it until I see it fire off.
