### ISSUE TITLE
Node 20 upgrade

### ISSUE THREAD

**Issue by arbrandes** [openedx/frontend-app-learner-record#298]
### Description

See the parent ticket for the general description and motivation, https://github.com/openedx/public-engineering/issues/267.  Make sure to follow its recommendations for each step of the process.

```[tasklist]
- [ ] https://github.com/openedx/frontend-app-learner-record/pull/396
- [ ] https://github.com/openedx/frontend-app-learner-record/pull/378
- [ ] https://github.com/openedx/frontend-app-learner-record/pull/397
- [ ] https://github.com/openedx/frontend-app-learner-record/pull/420
- [ ] https://github.com/openedx/frontend-app-learner-record/pull/436
```

**Comment by justinhynes** [comment]
It is my understanding that this upgrade will happen alongside other MFEs as part of https://github.com/openedx/public-engineering/issues/267. 

I'm not going to close this issue, but I'm not going to be tracking this as work Aperture needs to do as maintainers. I am assuming that there is a team/group of folks doing the updates as part of the public-engineering issue. (Please correct me if I'm wrong here!)

We are more than happy to verify and review the PR once the work is finished.
