### ISSUE TITLE
There is no “View as” block for Staff like this was done for an outdated page

### ISSUE THREAD

**Issue by DmytroAlipov** [openedx/frontend-app-learner-record#322]
![le_re](https://github.com/openedx/frontend-app-learner-record/assets/98233552/cfd14725-72b0-4ece-9b01-a5b88e3b95ec)

I haven't found the implementation of this functionality anywhere in this MFE code.
Could you please confirm if it's planned in the roadmap?
If so, approximately in which releases should we expect it?

**Comment by DmytroAlipov** [comment]
Hello @justinhynes 
Could you please tell me about this issue?

**Comment by justinhynes** [comment]
@DmytroAlipov When we were initially implementing the Learner Record MFE, we did not carry over the masquerading support. Masquerading support in the old Django template differs from masquerading support in edx-platform, which differs from the masquerading support implemented in the Learner Dashboard MFE too.

We had been hoping the community would solve the "add masquerading to MFEs" problem so we didn't have to reinvent the wheel again.

Instead, we extended the functionality of the Support Tools MFE, which allows admins to retrieve the contents of a user's Learner Record through the "Learner Records" tab after retrieving details for a specific user:
![image](https://github.com/openedx/frontend-app-learner-record/assets/3229735/85bbbe48-5bff-4a5f-86d1-29930140837e)

**Comment by DmytroAlipov** [comment]
@justinhynes Thank you very much for the detailed information 👍

**Comment by justinhynes** [comment]
@DmytroAlipov --I wanted to close to loop on this. I'm going to close this particular issue as I believe I have answered the questions you had.

If you'd like to open an official feature request to reconsider masquerading in the MFE, would you mind opening a new issue and we can track it accordingly?
