### ISSUE TITLE
LRMFE: Tutor support

### ISSUE THREAD

**Issue by hurtstotouchfire** [openedx/frontend-app-learner-record#97]
We're testing the MFE in Tutor and trying to figure out all the places to configure it properly.

**Comment by hurtstotouchfire** [comment]
https://github.com/overhangio/tutor-mfe/pull/63

**Comment by hurtstotouchfire** [comment]
Next step here will be adding tutor configuration information to the README.

**Comment by arbrandes** [comment]
This will add support for the MFE in tutor-credentials:

https://github.com/overhangio/tutor-credentials/pull/17
